name: wallet

services:
  account-server:
    container_name: account-server
    build: ./account-server
    ports:
      - "3030:3030"
    env_file:
      - ./account-server/.env
    depends_on:
      - account-postgres
    volumes:
      - ./account-server/docs/:/app/docs/
    develop:
      watch:
        - action: sync
          path: ./account-server/src
          target: /app/src

        - action: rebuild
          path: ./account-server/package.json
          target: /app/package.json

  account-postgres:
    container_name: account-postgres
    image: postgres:alpine3.20
    ports:
      - "5432:5432"
    volumes:
      - ./account-postgres/data:/var/lib/postgresql/data
    env_file:
      - ./account-postgres/.env
