name: wallet

services:
  account-server:
    container_name: account-server
    build: ./account-server
    ports:
      - "3000:80"
    env_file:
      - ./account-server/.env
    depends_on:
      - account-postgres
    develop:
      watch:
        - action: sync
          path: ./account-server/src
          target: /app/src
          ignore:
            - ./account-server/node_modules/

        - action: rebuild
          path: ./account-server/packege.json
          target: /app/package.json

  account-postgres:
    container_name: account-postgres
    image: postgres:alpine3.20
    ports:
      - "5432:5432"
    volumes:
      - ./account-postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=wallet
      - POSTGRES_USER=wallet
