name: wallet

services:
  account-server:
    build: ./account-server
    # ports:
    #   - 3000:3000
    env_file:
      - ./account-server/.env
    depends_on:
      - account-postgres
    volumes:
      - ./account-server/docs/:/app/docs/
    develop:
      watch:
        - action: sync
          path: ./account-server/src
          target: /app/src

        - action: rebuild
          path: ./account-server/package.json
          target: /app/package.json
    deploy:
      mode: replicated
      replicas: 5

  account-postgres:
    container_name: account-postgres
    image: postgres:alpine3.20
    ports:
      - "5432:5432"
    volumes:
      - ./account-postgres/data:/var/lib/postgresql/data
    env_file:
      - ./account-postgres/.env

  nginx:
    container_name: wallet-nginx
    build: ./nginx
    ports:
      - 4000:4000
    develop:
      watch:
        - action: sync+restart
          path: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf
    depends_on:
      - account-server
